[build]
#rustflags = ["-C", "force-frame-pointers", "-C", "target-cpu=native"]
rustflags = ["-C","target-cpu=native"]

[profile.bench] 
lto = "thin"
opt-level = 3
debug =1
codegen-units = 4

[profile.release]
lto = "thin"
opt-level = 3
debug =1
codegen-units = 4

